spring:
  application:
    name: new_pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_test
    username: root
    password: cc17715
mybatis-plus:
  configuration:
    #使用驼峰映射,防止以后忘记，这里还是记录一下好了： UserName = user_name user_name = user_name username = username
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: /api
  port: 8080
